### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by timomitchel** [VeeAndrade/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] I named my directories correctly. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [x] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [x] I broke down larger processes into smaller layers.
- [ ] I added and committed my changes with a properly formatted commit message starting with a present-tense verb and a capital letter.
Lowercase first word, but good job changing this on your last few commits. 
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [x] I structured and named my directories and files correctly.
- [x] The four attributes I chose for **Class #1** represent properties or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [x] The four methods I chose for **Class #1** represent behaviors or actions.
We would want these to be named in the present tense. So, `clean` instead of `cleaning`. 
- [x] I described what the methods do in **Class 1**, including which attributes they use or modify.
- [x] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message.
Not capitalized, but otherwise solid. 

Class #1 Example Object Checklist
- [x] The object I chose for **Class 1** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object.
I can tell that your methods are accurate here and you're only listing the result, but we would also like to see the method names again for clarity. 
- [x] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 

Class #2 Checklist
- [x] The four attributes I chose for **Class #2** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [ ] The four methods I chose for **Class #2** represent behaviors or actions.
It's tough for me to tell what the last two method names are? Also, it would be more clear what a method name is if you named it sanke case or camel case. So `add_food` or `adjustTemperature`
- [ ] I described what the methods do in **Class 2**, including which attributes they use or modify.
We want you to be more specific for the last two. So for the last method: `return_smart_fridge_value:` prints/returns current value of attribute `smart_fridge?`
- [x] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 

Class #2 Example Object Checklist
- [x] The object I chose for **Class 2** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message.

Hey Veronica! This assessment is solid and certainly passable. However, there are a few places that you could have been more clear with both your naming and your explanations. Please take a look at the feedback, and follow-up with questions if you have them! Good job!

### Assessment Results
- [x] Technical Ready
- [ ] Pending
- [ ] Not Technical Ready
